### ISSUE TITLE
[Umbrella] Add typing hints

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#847]
Now that EG no longer supports Python 2.x (and only supports 3.5+), we can add typing hints, which I've found helpful in other projects.   Given the size of coverage and the fact that this could be something to allow new contributors to get familiar with EG, its probably best to break this up into each of the "services" and let this issue act as an _umbrella issue_.

- [x] Add typing hints to kernel management and handlers (services/kernels) #848
- [x] Add typing hints to kernelspec handler (services/kernelspecs) #849
- [x] Add typing hints to session managers and handler (services/sessions) #850
- [x] Add typing hints to process proxies (services/processproxies) #851
- [x] Add typing hints to api handler (services/api) #852
- [x] Add typing hints to EG application (enterprisegatewayapp.py, mixins.py) #853

**Comment by kevin-bates** [comment]
We only have `services/kernels` left in this issue, any takers?

@kiersten-stokes, @bloomsa - you get first dibs.

**Comment by bloomsa** [comment]
`RemoteKernelManager` is kind of a doozy 😅 I don't have time this week but could maybe pick it up next week if no one else does

**Comment by kevin-bates** [comment]
No worries.  Given the interactions it has to make with jupyter_client and the proxies, I may take a stab at this one today or tomorrow.  Ping the issue next week if you haven't seen a PR and would like to work on it.  Thank you.

**Comment by kevin-bates** [comment]
Looks like all the sub-issues have been resolved, closing.  Thank you @kiersten-stokes and @bloomsa!
